#!/usr/bin/env python
# coding: utf-8

"""
Asciidoctor does not support enumeration of bibliography 
references. If we want an LaTeX like enumeration, we have
to go through all bibliography references in the XML
document and do our own enumeration.

Bibliography references written in Asciidoc
like: 

* [[[ID]]] REFERENCE

are rendered into the following XML code:

  <bibliomisc>
    <anchor xml:id="ID" xreflabel="[ID]"/>
      REFERENCE
  </bibliomisc>

a reference label might be specified:

* [[[ID,REF_LABEL]]] REFERENCE

which will be translated into the following XML code:

  <bibliomisc>
    <anchor xml:id="ID" xreflabel="[REF_LABEL]"/>
      REFERENCE
  </bibliomisc>
"""

import sys
import os

def enum_bibrefs (fname):
    collection = None
    try:
        from xml.dom.minidom import parse
        import xml.dom.minidom

        # Open XML document using minidom parser
        DOMTree = xml.dom.minidom.parse (fname)
        collection = DOMTree.documentElement
    except Exception as e:
        print (e, file=sys.stderr)
        print ("Cannot parse XML file {}!".format(fname), file=sys.stderr)
        exit (1)
    
    # Get all 'bibliomisc' elements
    bib_entries = collection.getElementsByTagName("bibliomisc")

    # replace reference labels
    i = 1
    for bib_entry in bib_entries:
        anchor = bib_entry.getElementsByTagName('anchor')[0]
        anchor.setAttribute ("xreflabel", "[%d]" % (i))
        i += 1

    # rename input file
    try:
        backup_fname = os.path.splitext (fname)[0] + ".bak"
        os.rename (fname, backup_fname)
    except Exception as e:
        print (e, file=sys.stderr)
        print ("Rename {} to {} failed!".format(fname, backup_fname), file=sys.stderr)
        exit (2)

    # write modified XML
    try:
        with open (fname, "w") as f:
            DOMTree.writexml(f)
    except Exception as e:
        print (e, file=sys.stderr)
        print ("Writing XML {} file failed".format(fname))
        exit (3)
        


# In[9]:


if __name__ == "__main__":
    try:
        ipy = get_ipython()
        sys.argv = [" ", "home.xml",]
    except:
        if len (sys.argv) == 0:
            print ("Missing argument!", file=sys.stderr)
            exit (1)

    enum_bibrefs (sys.argv[1])


# In[ ]:




